export const openingWaves = [
  { spawnTime: 3, enemyType: 'scout', enemyNumbers: 3, type: 'squadron' },
  { spawnTime: 5, position: [0, 0], enemyType: 'scout', enemyNumbers: 5, type: 'line', angle: 45, delay: 500, rotation: 135 },
  { spawnTime: 8, position: ['right', 0.7], enemyType: 'scout', enemyNumbers: 5, type: 'line', angle: 220, delay: 500, rotation: 310 },
  { spawnTime: 10, enemyType: 'scout', enemyNumbers: 5, type: 'squadron' },
  { spawnTime: 10, enemyType: 'redBomber', enemyNumbers: 3, type: 'squadron' },
  { spawnTime: 12, enemyType: 'scout', enemyNumbers: 7, type: 'squadron' },
  { spawnTime: 14, enemyType: 'scout', enemyNumbers: 9, type: 'squadron' },
  { spawnTime: 16, position: [0, 0.7], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 350, delay: 500, rotation: 440 },
  { spawnTime: 16, enemyType: 'redBomber', enemyNumbers: 5, type: 'squadron' },
  { spawnTime: 18, position: ['right', 0.5], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 180, delay: 500, rotation: 270 },
  { spawnTime: 18, position: [0, 0.4], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 360, delay: 500, rotation: 450 },
  { spawnTime: 20, enemyType: 'redBomber', leader: 'rogueLeader', enemyNumbers: 3, type: 'squadron' },
  { spawnTime: 20, position: [0, 0], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 45, delay: 500, rotation: 135 },
  { spawnTime: 21, position: [0, 1], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 315, delay: 500, rotation: 405 },
  { spawnTime: 22, position: ['right', 0], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 135, delay: 500, rotation: 225 },
  { spawnTime: 23, position: ['right', 1], enemyType: 'scout', enemyNumbers: 10, type: 'line', angle: 225, delay: 500, rotation: 315 },
  { spawnTime: 24, enemyType: 'redBomber', leader: 'rogueLeader', enemyNumbers: 5, type: 'squadron' },
  { spawnTime: 24, position: [0, 0.5], enemyType: 'scout', enemyNumbers: 3, type: 'line', angle: 360, delay: 250, rotation: 450 },
  { spawnTime: 26, position: [0, 0.6], enemyType: 'scout', enemyNumbers: 3, type: 'line', angle: 360, delay: 250, rotation: 450 },
  { spawnTime: 28, position: ['right', 0.4], enemyType: 'scout', enemyNumbers: 3, type: 'line', angle: 180, delay: 250, rotation: 270 },
  { spawnTime: 30, position: ['right', 0.7], enemyType: 'scout', enemyNumbers: 3, type: 'line', angle: 180, delay: 250, rotation: 270 },
  { spawnTime: 30, enemyType: 'redBomber', leader: 'rogueLeader', enemyNumbers: 7, type: 'squadron' },
];
